'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase-browser'
import { createRoomBookingsRepository, type RoomBooking, type RoomBookingDraft } from './data/room-bookings-repository'

const ROOMS = [
  { id: 1, name: 'Sala 1', floor: 'ground', color: '#D85A5A', x: 44.4, y: 5.7, width: 34, height: 41.7, capacity: 12, image: '/Assets/sale-riunioni/sala-1.jpg', description: 'Spazio per riunioni di gruppo e presentazioni.' },
  { id: 2, name: 'Sala 2', floor: 'ground', color: '#4A90E2', x: 78.1, y: 5.8, width: 20.6, height: 93.1, capacity: 8, image: '/Assets/sale-riunioni/sala-2.jpg', description: 'Sala luminosa per incontri e workshop.' },
  { id: 3, name: 'Sala 3', floor: 'first', color: '#4B7E5B', x: 21.3, y: 53.7, width: 12.1, height: 45.7, capacity: 8, image: '/Assets/sale-riunioni/sala-3.jpg', description: 'Ambiente riservato per riunioni operative.' },
  { id: 4, name: 'Sala 4', floor: 'first', color: '#E8935C', x: 33.6, y: 53.7, width: 12.6, height: 45.7, capacity: 6, image: '/Assets/sale-riunioni/sala-4.jpg', description: 'Sala raccolta per conversazioni e videochiamate.' },
]
const FLOORS = [{ key: 'ground', label: 'Piano Terra', image: '/Assets/piano terra.png' }, { key: 'first', label: 'Primo Piano', image: '/Assets/primo piano.png' }]
type Room = typeof ROOMS[number]

const timeToMinutes = (time: string) => { const [hours, minutes] = time.split(':').map(Number); return hours * 60 + minutes }
const endTime = (booking: Pick<RoomBooking, 'timeStart' | 'duration'>) => { const end = timeToMinutes(booking.timeStart) + booking.duration; return `${String(Math.floor(end / 60)).padStart(2, '0')}:${String(end % 60).padStart(2, '0')}` }
const overlaps = (draft: RoomBookingDraft, booking: RoomBooking) => draft.roomId === booking.roomId && draft.date === booking.date && timeToMinutes(draft.timeStart) < timeToMinutes(booking.timeStart) + booking.duration && timeToMinutes(draft.timeStart) + draft.duration > timeToMinutes(booking.timeStart)

function Header() { return <header className="border-b border-gray-300 bg-white shadow-sm"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-6"><div><h1 className="text-3xl font-bold tracking-tight text-dark">Prenotazione Sale Riunioni</h1><p className="mt-1 text-sm text-gray-500">Il tuo spazio, quando ti serve</p></div><img src="/Assets/Logo True.png" alt="True Design" className="h-14 w-auto" /></div></header> }

function RoomCard({ room, count, onSelect }: { room: Room; count: number; onSelect: () => void }) { return <button type="button" onClick={onSelect} className="overflow-hidden rounded-xl border border-gray-200 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-dark"><div className="relative aspect-[4/3]"><img src={room.image} alt={`${room.name}, sala riunioni True Design`} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-y-0 left-0 w-1" style={{ backgroundColor: room.color }} /></div><div className="p-4"><div className="flex gap-2"><span aria-hidden="true" className="mt-1 h-2 w-2 rounded-full" style={{ backgroundColor: room.color }} /><p className="font-semibold text-dark">{room.name}</p><span className="ml-auto text-xs text-gray-400">fino a {room.capacity}</span></div><p className="mt-2 text-xs text-gray-500">{room.description}</p><p className="mt-2 text-xs text-gray-400">{count} prenotazion{count === 1 ? 'e' : 'i'} · Prenota</p></div></button> }

function FloorPlan({ bookings, onSelect }: { bookings: RoomBooking[]; onSelect: (room: Room) => void }) { const [hovered, setHovered] = useState<number | null>(null); return <div className="space-y-10"><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{ROOMS.map(room => <RoomCard key={room.id} room={room} count={bookings.filter(item => item.roomId === room.id).length} onSelect={() => onSelect(room)} />)}</div><div className="grid grid-cols-1 gap-6 lg:grid-cols-2">{FLOORS.map(floor => <div key={floor.key}><h2 className="mb-3 text-lg font-semibold text-dark">{floor.label}</h2><div className="relative overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm"><img src={floor.image} alt={floor.label} className="block w-full" /><svg className="absolute inset-0 h-full w-full">{ROOMS.filter(room => room.floor === floor.key).map(room => <g key={room.id} onMouseEnter={() => setHovered(room.id)} onMouseLeave={() => setHovered(null)} onClick={() => onSelect(room)} style={{ cursor: 'pointer' }}><rect x={`${room.x}%`} y={`${room.y}%`} width={`${room.width}%`} height={`${room.height}%`} fill={room.color} opacity={hovered === room.id ? .5 : .3} stroke={room.color} strokeWidth={hovered === room.id ? 3 : 2} />{hovered === room.id && <text x={`${room.x + room.width / 2}%`} y={`${room.y + room.height / 2}%`} textAnchor="middle" dominantBaseline="middle" fontSize="20" fontWeight="bold">{room.name}</text>}</g>)}</svg></div></div>)}</div></div> }

function BookingModal({ room, bookings, initial, saving, onClose, onSubmit }: { room: Room; bookings: RoomBooking[]; initial: RoomBooking | null; saving: boolean; onClose: () => void; onSubmit: (draft: RoomBookingDraft) => Promise<void> }) {
  const [name, setName] = useState(initial?.name ?? ''); const [date, setDate] = useState(initial?.date ?? ''); const [timeStart, setTimeStart] = useState(initial?.timeStart ?? ''); const [duration, setDuration] = useState(String(initial?.duration ?? 30)); const [description, setDescription] = useState(initial?.description ?? ''); const [error, setError] = useState('')
  const submit = async () => { const draft = { roomId: room.id, name: name.trim(), date, timeStart, duration: Number(duration), description: description.trim() }; const day = date ? new Date(`${date}T12:00:00`).getDay() : -1; if (!draft.name || !date || !timeStart) return setError('Inserisci nome, data e ora di inizio.'); if (day === 0 || day === 6) return setError('Le prenotazioni sono disponibili dal lunedì al venerdì.'); if (timeToMinutes(timeStart) + draft.duration > 1080) return setError('La riunione deve terminare entro le 18:00.'); if (bookings.some(booking => booking.id !== initial?.id && overlaps(draft, booking))) return setError('La sala è già prenotata in questa fascia oraria.'); setError(''); await onSubmit(draft) }
  const input = 'mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-dark focus:border-dark focus:outline-none focus:ring-2 focus:ring-gray-200'; const times = Array.from({ length: 20 }, (_, i) => `${String(8 + Math.floor(i / 2)).padStart(2, '0')}:${i % 2 ? '30' : '00'}`)
  return <div role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !saving) onClose() }} className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="booking-title" className="w-full max-w-md space-y-4 rounded-xl bg-white p-6 shadow-lg"><div><h2 id="booking-title" className="text-2xl font-bold text-dark">{initial ? `Modifica · ${room.name}` : room.name}</h2><p className="mt-1 text-sm text-gray-600">{initial ? 'Aggiorna i dettagli della riunione.' : 'Compila i dettagli della prenotazione.'}</p></div><label className="block text-sm font-medium text-dark">Il tuo nome<input value={name} onChange={event => setName(event.target.value)} className={input} /></label><label className="block text-sm font-medium text-dark">Data<input type="date" min={new Date().toISOString().split('T')[0]} value={date} onChange={event => setDate(event.target.value)} className={input} /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium text-dark">Ora inizio<select value={timeStart} onChange={event => setTimeStart(event.target.value)} className={input}><option value="">Seleziona</option>{times.map(time => <option key={time}>{time}</option>)}</select></label><label className="block text-sm font-medium text-dark">Durata<select value={duration} onChange={event => setDuration(event.target.value)} className={input}>{[30, 60, 90, 120, 150, 180].map(value => <option key={value} value={value}>{value === 60 ? '1 ora' : `${value} minuti`}</option>)}</select></label></div><label className="block text-sm font-medium text-dark">Note <span className="font-normal text-gray-500">(opzionale)</span><textarea value={description} onChange={event => setDescription(event.target.value)} rows={2} className={input} /></label>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">{error}</p>}<div className="flex gap-2 pt-2"><button type="button" disabled={saving} onClick={onClose} className="min-h-11 flex-1 rounded-lg border border-gray-300 px-4 py-2 font-medium text-dark hover:bg-gray-50 disabled:opacity-50">Annulla</button><button type="button" disabled={saving} onClick={() => void submit()} className="min-h-11 flex-1 rounded-lg bg-dark px-4 py-2 font-medium text-white hover:opacity-90 disabled:opacity-50">{saving ? 'Salvataggio…' : initial ? 'Salva modifiche' : 'Conferma prenotazione'}</button></div></div></div>
}

function BookingsList({ bookings, userId, isAdmin, loading, onEdit, onDelete }: { bookings: RoomBooking[]; userId: string | null; isAdmin: boolean; loading: boolean; onEdit: (booking: RoomBooking) => void; onDelete: (booking: RoomBooking) => void }) { const today = new Date().toISOString().split('T')[0]; const upcoming = bookings.filter(booking => booking.date >= today).sort((a, b) => `${a.date}T${a.timeStart}`.localeCompare(`${b.date}T${b.timeStart}`)); return <section className="space-y-4 rounded-lg border border-gray-200 bg-white p-6 shadow-sm"><div><h2 className="text-lg font-semibold text-dark">Prenotazioni in programma</h2><p className="text-sm text-gray-500">{loading ? 'Caricamento prenotazioni condivise…' : upcoming.length ? `${upcoming.length} prenotazion${upcoming.length === 1 ? 'e' : 'i'} · aggiornate in tempo reale` : 'Nessuna prenotazione'}</p></div><div className="space-y-3">{upcoming.map(booking => { const room = ROOMS.find(item => item.id === booking.roomId); const canManage = isAdmin || booking.createdBy === userId; return <div key={booking.id} className="flex gap-3 rounded-lg border border-gray-200 p-3"><span aria-hidden="true" className="mt-1.5 h-3 w-3 shrink-0 rounded-full" style={{ backgroundColor: room?.color }} /><div className="min-w-0 flex-1"><p className="font-medium text-dark">{room?.name} · {booking.name}</p><p className="text-xs text-gray-500">{new Date(`${booking.date}T12:00:00`).toLocaleDateString('it-IT', { weekday: 'short', day: 'numeric', month: 'short' })} · {booking.timeStart}–{endTime(booking)}</p>{booking.description && <p className="mt-1 text-xs text-gray-600">{booking.description}</p>}</div>{canManage && <div className="flex shrink-0 gap-2"><button type="button" onClick={() => onEdit(booking)} className="min-h-11 rounded border border-gray-300 px-3 text-xs font-medium text-dark hover:bg-gray-100">Modifica</button><button type="button" onClick={() => onDelete(booking)} className="min-h-11 rounded border border-red-200 px-3 text-xs font-medium text-red-700 hover:bg-red-50">Elimina</button></div>}</div> })}</div></section> }

export default function PrenotazioneSaleRiunioniPage() {
  const supabase = useMemo(() => createClient(), []); const repository = useMemo(() => createRoomBookingsRepository(supabase), [supabase]); const [bookings, setBookings] = useState<RoomBooking[]>([]); const [room, setRoom] = useState<Room | null>(null); const [editing, setEditing] = useState<RoomBooking | null>(null); const [userId, setUserId] = useState<string | null>(null); const [isAdmin, setIsAdmin] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [status, setStatus] = useState<{ kind: 'success' | 'error'; message: string } | null>(null)
  const loadBookings = useCallback(async () => { try { setBookings(await repository.list()) } catch (error) { setStatus({ kind: 'error', message: error instanceof Error ? error.message : 'Impossibile caricare le prenotazioni.' }) } finally { setLoading(false) } }, [repository])
  useEffect(() => { void loadBookings(); void supabase.auth.getUser().then(async ({ data: { user } }) => { setUserId(user?.id ?? null); if (user) { const { data } = await supabase.from('profiles').select('is_admin').eq('id', user.id).maybeSingle(); setIsAdmin(Boolean(data?.is_admin)) } }); const channel = supabase.channel('room-bookings-live').on('postgres_changes', { event: '*', schema: 'public', table: 'room_bookings' }, () => { void loadBookings() }).subscribe(); return () => { void supabase.removeChannel(channel) } }, [loadBookings, supabase])
  const close = () => { if (!saving) { setRoom(null); setEditing(null) } }; const save = async (draft: RoomBookingDraft) => { setSaving(true); try { const stored = editing ? await repository.update(editing.id, draft) : await repository.create(draft); setBookings(current => editing ? current.map(item => item.id === stored.id ? stored : item) : [...current, stored]); setStatus({ kind: 'success', message: editing ? 'Prenotazione aggiornata correttamente.' : 'Prenotazione condivisa con tutti gli utenti autorizzati.' }); setRoom(null); setEditing(null) } catch (error) { setStatus({ kind: 'error', message: error instanceof Error ? error.message : 'Impossibile salvare la prenotazione.' }) } finally { setSaving(false) } }; const remove = async (booking: RoomBooking) => { if (!window.confirm(`Eliminare la prenotazione di ${booking.name}?`)) return; try { await repository.remove(booking.id); setBookings(current => current.filter(item => item.id !== booking.id)); setStatus({ kind: 'success', message: 'Prenotazione eliminata.' }) } catch (error) { setStatus({ kind: 'error', message: error instanceof Error ? error.message : 'Impossibile eliminare la prenotazione.' }) } }
  return <div className="min-h-screen bg-cream text-dark"><Header /><main className="mx-auto max-w-7xl space-y-10 px-4 py-8"><div><h2 className="mb-8 text-3xl font-bold tracking-tight text-dark">Seleziona una sala</h2><FloorPlan bookings={bookings} onSelect={selected => { setRoom(selected); setEditing(null); setStatus(null) }} /></div>{status && <div role="status" className={`rounded-lg border px-4 py-3 text-sm font-medium ${status.kind === 'success' ? 'border-green-200 bg-green-50 text-green-800' : 'border-red-200 bg-red-50 text-red-800'}`}>{status.message}</div>}<BookingsList bookings={bookings} userId={userId} isAdmin={isAdmin} loading={loading} onEdit={booking => { const selected = ROOMS.find(item => item.id === booking.roomId); if (selected) { setRoom(selected); setEditing(booking) } }} onDelete={remove} /></main>{room && <BookingModal room={room} bookings={bookings} initial={editing} saving={saving} onClose={close} onSubmit={save} />}</div>
}
